### ISSUE TITLE
Create a glossary to be followed in the translation process

### ISSUE THREAD

**Issue by theBstar** [javascript-tutorial/hi.javascript.info#21]
### Changed:

- Editor  -  एडिटर, If you like, you can provide { संपादक } in braces.
- Transpiled - रूपांतरित
- Integration - एकीकरण 
- Execute - निष्पादित
- Optimise - अनुकूलन
- Compiled - संकलित
- Logical - तार्किक
- Operator - संचालक

### Unchanged:
- Most of the technical term & entities

**Comment by utsav91** [comment]
Hi, this is Utsav

**Comment by theBstar** [comment]
> Hi, this is Utsav

hey @utsav91 I am assigning the issue to you. You can come up with a plan for this & I will update the issue accordingly.

**Comment by theBstar** [comment]
@ayushhagarwal this is where we will populate our glossary. @utsav91 is going to lead us on this. This needs to be done carefully. Looking forward to your contribution. Let us know if you need any help.

**Comment by utsav91** [comment]
@theBstar @ayushhagarwal If you guys have started translating already, you can just comment the words here which you think should be left as is or not translated.

You can also include suggestions for some words if you have any.

I'll include them as well.

The glossary would be a living document, at least for the next couple of weeks. 

I would try to come up with a first iteration during the weekend.

**Comment by ayushhagarwal** [comment]
Please write editor as एडिटर.
Or if you are using संपादक use it with braces like : { संपादक }

**Comment by theBstar** [comment]
Hi @ashpratap007 , It would be great if you could comment, the technical terms which had been updated with the article you translated.

**Comment by Nirbhayparmar** [comment]
Logical - तार्किक
Operator - संचालक

**Comment by Nirbhayparmar** [comment]
is there any file for glossary?

**Comment by theBstar** [comment]
Not yet, but having a file might help, What do you suggest @Nirbhayparmar

**Comment by Nirbhayparmar** [comment]
It is necessary because if any one wants to check some word then it is easy to have all the word in a single file.

**Comment by theBstar** [comment]
Makes sense, Let's add a file on the root dir then. I will create an issue for this. I will only be able to do it this Sunday,  Let me know if you want to take this up,

**Comment by theBstar** [comment]
We will use [glossary.md](https://github.com/javascript-tutorial/hi.javascript.info/blob/master/glossary.md) file for further development.
