### ISSUE TITLE
Create a glossary file on root dir

### ISSUE THREAD

**Issue by theBstar** [javascript-tutorial/hi.javascript.info#64]
- Create a glossary file on root dir
 - Move everything from issue #21 
 - Go though the translated articles and add any missing term

**Comment by Nirbhayparmar** [comment]
@theBstar the glossary file created as [glossary.md](https://github.com/javascript-tutorial/hi.javascript.info/files/6564508/glossary.md)in root directory.
Can I send a pull request?
